--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: like Hash#values_at
full_name: Rack::Request#values_at
is_singleton: false
name: values_at
params: (*keys)
visibility: public
