--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Answers with values for given keys by sending each to self
full_name: Ramaze::GlobalStruct#values_at
is_singleton: false
name: values_at
params: (*keys)
visibility: public
