--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: return the values for given keys.
full_name: Ramaze::YAMLStoreCache#values_at
is_singleton: false
name: values_at
params: (*keys)
visibility: public
