# -*- mode:ruby; indent-tabs-mode:nil; coding:utf-8 -*-
# vim:ts=2:sw=2:expandtab:
require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/testtask'
require 'pathname'

# Application own Settings
APPNAME               = "Fenestra"
TARGET                = "#{APPNAME}.app"
APPVERSION            = Time.now.strftime("%Y-%m-%d")
PUBLISH               = 'yourname@yourhost:path'
CONFIGURATION         = ENV['Configuration'] || 'Debug'
EXECUTABLE            = "build/#{CONFIGURATION}/#{TARGET}/Contents/MacOS/#{APPNAME}"

# Tasks
task :default => [:run]

task :test do
  system("cd test; rake")
end


desc "Build the #{CONFIGURATION} configuration and run it."
task :run => [:build, :preactivate] do
  %x{ #{EXECUTABLE} }
end

desc "Make sure the app is brought to the front once launched."
# Taken from Rucola
task :preactivate do
  require 'osx/cocoa'
  Thread.new do
    sleep 0.025 until OSX::NSWorkspace.sharedWorkspace.launchedApplications.any? {|dict| dict['NSApplicationName'] == APPNAME }
    `osascript -e 'tell application "#{EXECUTABLE}" to activate'`
  end
end

desc "Build the selected Configuration (#{CONFIGURATION})."
task :build => "xcode:build:#{APPNAME}:#{CONFIGURATION}"

desc 'Deep clean of Debug and Release'
task :clean  do
  puts %x{ xcodebuild -alltargets -configuration Debug clean }
  puts %x{ xcodebuild -alltargets -configuration Release clean }
end


desc "Create a disk image for Release version of the application."
task :package => [:clean, "xcode:build:#{APPNAME}:Release", :pkg] do
  name="#{APPNAME}.#{APPVERSION}"
  src="build/Release/#{TARGET}"
  sh %{
  hdiutil create -volname '#{name}' -srcfolder #{src} pkg/'#{name}'.dmg
  }
end

directory 'pkg'


desc 'Make Localized nib from English.lproj and Lang.lproj/nib.strings'
rule(/.nib$/ => [proc {|tn| File.dirname(tn) + '/nib.strings' }]) do |t|
  p t.name
  lproj = File.dirname(t.name)
  target = File.basename(t.name)
  rm_rf t.name
  sh %{
  nibtool -d #{lproj}/nib.strings -w #{t.name} English.lproj/#{target}
  }
end

# [Rubycocoa-devel 906] dynamically xcode rake tasks
# [Rubycocoa-devel 907]
#
def xcode_targets
  out = %x{ xcodebuild -list }
  out.scan(/.*Targets:\s+(.*)Build Configurations:.*/m)

  targets = []
  $1.each_line do |l|
    l = l.strip.sub(' (Active)', '')
    targets << l unless l.nil? or l.empty?
  end
  targets
end

def xcode_configurations
  out = %x{ xcodebuild -list }
  out.scan(/.*Build Configurations:\s+(.*)If no build configuration.*/m)

  configurations = []
  $1.each_line do |l|
    l = l.strip.sub(' (Active)', '')
    configurations << l unless l.nil? or l.empty?
  end
  configurations
end

namespace :xcode do
 targets = xcode_targets
 configs = xcode_configurations

 %w{build clean}.each do |action|
   namespace "#{action}" do

     targets.each do |target|
       desc "#{action} #{target}"
       task "#{target}" do |t|
         puts %x{ xcodebuild -target '#{target}' #{action} }
       end

       # alias the task above using a massaged name
       massaged_target = target.downcase.gsub(/[\s*|\-]/, '_')
       task "#{massaged_target}" => "xcode:#{action}:#{target}"


       namespace "#{target}" do
         configs.each do |config|
           desc "#{action} #{target} #{config}"
           task "#{config}" do |t|
             puts %x{ xcodebuild -target '#{target}' -configuration '#{config}' #{action} }
           end
         end
       end

       # namespace+task aliases of the above using massaged names
       namespace "#{massaged_target}" do
         configs.each { |conf| task "#{conf.downcase.gsub(/[\s*|\-]/, '_')}" => "xcode:#{action}:#{target}:#{conf}" }
       end

     end

   end
 end
end


