# -*- mode:ruby; indent-tabs-mode:nil; coding:utf-8 -*-
# vim:ts=2:sw=2:expandtab:
require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/testtask'
require 'pathname'

task :default => :test

desc "Run tests."
Rake::TestTask.new do | t |
  t.test_files = FileList['**/*tests.rb']
end

