# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22c7c0384df45478ea931d2fd7fdfe06a26bacfb2d16031b33a49e0421096f1c2230be6bf9c9f9bda37e8975cfbaeb78e596971355879f9865cb4d31d62612f7

test:
  secret_key_base: 4e67ef372300340ce6bd8a98b5ff07212652b48630b57c454f3294b1d6b2a069f09672c64a53037d4c78a69e2d7e3a4ad014679fcea8ab6d35f8aa6d7be654e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
