# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'chunky_png'

gem 'ruby-progressbar'

gem 'highline'

gem 'gtk3'

gem 'opengl'
